[project]
name = "stepguard"
version = "1.1.0"
description = "Real-time phone usage detection system on staircases Developed using **YOLO + OpenCV** with alert notifications and violator image logging to database"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.0",
    "dotenv>=0.9.9",
    "onnx>=1.19.0",
    "onnxruntime>=1.23.0",
    "onnxslim>=0.1.69",
    "opencv-python>=4.12.0.88",
    "ultralytics>=8.3.203",
]
