WEIGHTS_DIR = "./model"
MODEL_NAME = "guard.pt"

MODEL_CONF = 0.7
CONTAINMENT_RATIO = 0.5
PERSON_PAD_PX = 10

PERSON_ALIASES = {"Normal"}
ALERT_CLASSES = {"Phone"}

VIDEO_PATH = "./video"
VIDEO_NAME = "/20250815_131431.mp4"

SNAPSHOT_DIR = "./snapshots"  
PHONE_HOLD_SECONDS = 4

alert_cooldown = 5

INFER = 10